// Bundles prompts/<version>/*.md into src/lib/ai/prompts.generated.ts so the prompt text
// ships inside the serverless bundle (no runtime fs reads) and is versioned with the code.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { resolve } from "node:path";

export const PROMPT_VERSION = "v1";

const root = resolve(import.meta.dirname, "..");
const dir = resolve(root, "prompts", PROMPT_VERSION);
const read = (name) => readFileSync(resolve(dir, name), "utf8");

const out = `// GENERATED by scripts/build-prompts.mjs — do not edit. Source: prompts/${PROMPT_VERSION}/
export const PROMPT_VERSION = ${JSON.stringify(PROMPT_VERSION)};
export const SYSTEM_PROMPT = ${JSON.stringify(read("system.md"))};
export const ANALYSIS_USER_TEMPLATE = ${JSON.stringify(read("analysis_user.md"))};
export const NEWS_SEARCH_TEMPLATE = ${JSON.stringify(read("news_search.md"))};
`;

const target = resolve(root, "src/lib/ai/prompts.generated.ts");
mkdirSync(resolve(root, "src/lib/ai"), { recursive: true });
const current = existsSync(target) ? readFileSync(target, "utf8") : "";
if (current !== out) {
  writeFileSync(target, out);
  console.log(`prompts bundled (${PROMPT_VERSION}) -> src/lib/ai/prompts.generated.ts`);
}
