import type { Metadata } from "next";
export const metadata: Metadata = { title: "Privacy Policy" };

export default function PrivacyPage() {
  return (
    <article className="max-w-2xl mx-auto text-sm leading-relaxed space-y-4">
      <h1 className="text-2xl font-semibold">Privacy Policy</h1>
      <p className="text-muted">Last updated: 2026.</p>
      <h2 className="text-lg font-semibold">What we store</h2>
      <p>When you sign in we store your email, name, and profile image from your sign-in provider, plus the watchlists, saved screens, and analysis history you create. We log which analyses you trigger to enforce per-account quotas and to bill our own AI usage — never sold or shared.</p>
      <h2 className="text-lg font-semibold">Cookies</h2>
      <p>We use a single session cookie to keep you signed in and a local browser flag to remember that you dismissed the cookie notice. No advertising or cross-site tracking cookies.</p>
      <h2 className="text-lg font-semibold">Third parties</h2>
      <p>Market data comes from third-party providers (e.g. Yahoo Finance). AI analysis is generated by Anthropic&rsquo;s Claude API from that data. We do not send your personal information to these providers — only the ticker being analyzed.</p>
      <h2 className="text-lg font-semibold">Your data</h2>
      <p>You can delete your watchlists and saved screens at any time. To delete your account and associated data, contact the site owner.</p>
    </article>
  );
}
